### PR TITLE
Fix google maps test

### PR DESCRIPTION
**Pull request by NiallBunting**
Seems google has changed its description. Update the test to reflect
this.

Not sure if you want contributions. I hope you don't mind.

### CODE REVIEW

**Comment by NiallBunting** [comment]
The figaro tests seem to time out quite often but sometimes will pass. Was not sure how to go about making them work more reliably.

**Review by kapouer — COMMENTED** [review]
It seems gmaps return different results based on your location. I run the tests from France so i don't get the country :) The test should check description to start with 86000.

**Comment by NiallBunting** [comment]
@kapouer Hopefully, that works for you as well in France.

**Comment by kapouer** [comment]
Thanks !

**Pull request merged**
